"""init

Revision ID: 5e88a7828202
Revises: 
Create Date: 2018-12-21 22:53:32.994794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e88a7828202'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('function',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('qq', sa.String(length=15), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('fast_mail_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('price', sa.String(length=16), nullable=False),
    sa.Column('postage', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(length=200), nullable=True),
    sa.Column('choicest', sa.Integer(), nullable=True),
    sa.Column('has_goods', sa.Integer(), nullable=True),
    sa.Column('supply_id', sa.Integer(), nullable=True),
    sa.Column('age_group_id', sa.Integer(), nullable=True),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_group.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['function.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supply.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('func_age',
    sa.Column('func_id', sa.Integer(), nullable=True),
    sa.Column('age_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['age_id'], ['age_group.id'], ),
    sa.ForeignKeyConstraint(['func_id'], ['function.id'], )
    )
    op.create_table('banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('validate', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('c_time', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('banner')
    op.drop_table('func_age')
    op.drop_table('book')
    op.drop_table('supply')
    op.drop_table('function')
    op.drop_table('age_group')
    # ### end Alembic commands ###
